### ISSUE TITLE
Output of the bruteforce script

### ISSUE THREAD

**Issue by sebiXY** [francozappa/knob#11]
Hello,

I am trying to understand what the output of the brute force script is. As far as I understand, in the terminal output it shows what pattern it was able to decrypt from the ciphertexts in the **cts.py** file with the brute forced key:
`2021-02-01 16:31:57,580 root INFO attack i:     208655, off: 24, CLK_HEX: 032f0f, MATCH jpeg 'jpeg' at [301]). `
![Screenshot from 2021-02-02 15-51-12](https://user-images.githubusercontent.com/26957426/106617677-22874e00-656f-11eb-9514-95f61af66a8d.png)
If I check the **.bf** file after the script is finished, i can find the corresponding lines:
![132](https://user-images.githubusercontent.com/26957426/106618408-b78a4700-656f-11eb-94fd-1c8ee53e608c.png)

What does “CLK”, “off” and “out” of the .bf file displays? And is there a way to get the actual brute forced key and the decrypted messages?

Thank you in advance

**Comment by spanalytics** [comment]
Hello,

 

I can help a little (if I remember correctly):

-CLK is the CLK_N 26-1 calculated from the CLK_N 27-0 that you provide to the python script

-off is the offset added to the CLK_N value and passed to E0.  In our testing, this should not be necessary if you are passing in the right clock value (unless you aren’t sure about it).

-out is the decrypted “plain text” or decrypted message

 

If you look at bf.py you’ll see where Kc is calculated, assuming that’s the key you are referring to.

 

Hope that helps,

Mark

**Comment by sebiXY** [comment]
Thanks!
