### ISSUE TITLE
Ubertooth, è necessario? - Ubertooth, is necessary?

### ISSUE THREAD

**Issue by aleberello** [francozappa/knob#3]
Ciao, innanzitutto volevo farti i miei complimenti per questo lavoro, è davvero interessante ed utile!
Stavo provando a riprodurre il codice utilizzando uno Z3 Compact che da quanto ho capito dalla documentazione di Internalblue dovrebbe avere lo stesso chip bluetooth del Nexus 5.
Per ora non riesco ancora a far funzionare correttamente Internalblue (il bluetooth crasha quando cerco di fare una accoppiamento con un altro dispositivo).

Quello che però non mi è chiaro leggendo il paper e la documentazione del repo è se il bluetooth sniffer (Ubertooth) è necessario per manipolare la procedura di negoziazione dell'entropia per la chiave K'c. 
Inoltre non mi è chiaro se sia o meno possibile, una volta trovata forzata la chiave, recuperare i pacchetti trasferiti direttamente da Wireshark utilizzando Internalblue sul dispositivo modificato (Nexus 5 - Z3 Compact) e leggendo il log "btsnoop_hci.log".

Mi scuso per le domande, forse banali, e per l'inglese orribile con cui tradurrò questo messaggio per il resto della community.
Grazie e buona giornata!
Alessandro

-------------------------------------------------------------
(ENG)

Hi, first of all congrats for this useful research, it's really interesting!
I was trying to reproduce your code using a Z3 Compact that should share the same bluetooth chip of the Nexus 5 (i found this information on the Internalblue repo).
For now I can't get Internalblue to work properly (bluetooth crashes when I try to pair with another device).

What is not clear to me, after reading your paper and the documentation of the repo, is whether the bluetooth sniffer (Ubertooth) is necessary to manipulate the entropy negotiation procedure for the K'c key or not.
Furthermore, it is not clear to me whether or not it is possible, once the key has been forced, to recover the packets transferred directly from Wireshark using Internalblue on the modified device (Nexus 5 - Z3 Compact) and reading them the log file "btsnoop_hci.log".

I apologize for the trivial questions and for the horrible English with which I will translate this message for the rest of the community.
Thank you and have a good day!
Alessandro

**Comment by francozappa** [comment]
Ciao Alessandro,

Ti rispondo in inglese cosi rimane più utile ad un pubblico più ampio.

You don't need Ubertooth to manipulate the key negotiation protocol. The key negotiation is manipulated by a patch in the Nexus 5 firmware that is added using internalblue. Ubertooth can be used as an over-the-air Bluetooth BR/EDR sniffer. Keep in mind that it is a best effort sniffing and it is not going to capture all packets and their metadata..

You can access the HCI packets from the modified (patched) device by enabling HCI snoop logging functionality in the Android developer options. Once you enable it, you can find the capture file in the phone filesystem, pull it, and analyze it on your PC with Wireshark or similar. Alternatively you can access the HCI packets by enabling HCI monitoring in internalblue. For the LMP packets you can capture and analyze them using internalblue's LMP monitoring.

I hope that the answer is clear, and thanks for your interest!

**Comment by francozappa** [comment]
Ciao @Aleberello ,

Posso chiudere l'issue?

**Comment by aleberello** [comment]
Ciao @francozappa,
scusa per il ritardo! Sì puoi chiudere, grazie mille per la spiegazione, sei stato molto gentile.
Buona giornata,
Alessandro

Hi,
sorry for my late reply.
Thank you very much for the clarification!
