### ISSUE TITLE
LMP dissection plugin

### ISSUE THREAD

**Issue by SamZorSec** [francozappa/knob#4]
Hello @francozappa,
Which plugin(s) (standard/legacy, btbb/btbredr) are you using to dissect the LMP packets? I can see only Ethernet II frames (Wireshark 2.6.8, Ubuntu 18.04) and I get an error while launching Wireshark.

```
Optionally install the LMP dissection plugin and our LMP coloring rules to easily follow the packet capture. I was able to install using Wireshark v2.6.10
```

The error:
```
btbb.so: undefined symbol: new_create_dissector_handle
```
I know it's not an error related to this project, but could you please share your modifications? Thanks a lot.,
Sam

**Comment by francozappa** [comment]
Hi @mertenats,

This is the [plugin](https://github.com/greatscottgadgets/libbtbb) that I'm using, and I had to downgrade Wireshark to version 2.6.6 to compile it. Once the plugin is installed and you can see the decoded LMP packets you can also add the [coloring rules](https://github.com/francozappa/knob/tree/master/wireshark) to get a nicer UI.

**Comment by SamZorSec** [comment]
Thanks @francozappa, I'll give it a try.

**Comment by SamZorSec** [comment]
I've installed Wireshark 2.6.6 and libtbb, but I still have `Ethernet II` frames in Wireshark ...

Download and install Wireshark 2.6.6 :
```
wget https://www.wireshark.org/download/src/all-versions/wireshark-2.6.6.tar.xz
tar xf wireshark-2.6.6.tar.xz
cd wireshark-2.6.6/
mkdir build
cd build
cmake ..
make
sudo make install
```

Download and install libtbb :
```
git clone https://github.com/greatscottgadgets/libbtbb.git
cd libbtbb
mkdir build
cd build
cmake ..
make
sudo make install
```

Output :
```
sudo make install
[ 88%] Built target btbb
[ 88%] Built target btaptap
[100%] Built target pcapdump
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/pkgconfig/libbtbb.pc
-- Installing: /usr/local/lib/libbtbb.so.1.0
-- Up-to-date: /usr/local/lib/libbtbb.so.1
-- Up-to-date: /usr/local/lib/libbtbb.so
-- Installing: /usr/local/include/btbb.h
running build
running build_py
running install
running install_lib
copying /home/samuel/Downloads/libbtbb/build/python/pcaptools/build/lib.linux-x86_64-2.7/pcapdump/__init__.py -> //usr/local/lib/python2.7/site-packages/pcapdump
copying /home/samuel/Downloads/libbtbb/build/python/pcaptools/build/lib.linux-x86_64-2.7/pcapdump/pcapdump.py -> //usr/local/lib/python2.7/site-packages/pcapdump
byte-compiling //usr/local/lib/python2.7/site-packages/pcapdump/__init__.py to __init__.pyc
byte-compiling //usr/local/lib/python2.7/site-packages/pcapdump/pcapdump.py to pcapdump.pyc
running install_egg_info
Removing //usr/local/lib/python2.7/site-packages/pcapdump-0.0.0-py2.7.egg-info
Writing //usr/local/lib/python2.7/site-packages/pcapdump-0.0.0-py2.7.egg-info
-- Installing: /usr/local/bin/btaptap
```

Do I am missing something ?

**Comment by francozappa** [comment]
I'm sorry but I'm not using Ubuntu and I did not compile Wireshark from source.

Maybe you are missing some dependencies or you have to add some extra flag to the `Makefile` to support plugins? Do you get the same problem if you install the same Wireshark version with your package manager?

**Comment by SamZorSec** [comment]
Did you install only `libtbb`, not the plugins in the `wireshark` sub-folder?  Which release of `libtbb` are you using? Did you specify something by right clicking on a packet (right click > Decode as -> ) ?

I have the same behavior with a compiled version and the version from the package manager.

Thanks in advance

**Comment by francozappa** [comment]
Maybe you can try to install it from [here](https://github.com/demantz/lmp_wireshark_dissector)

I installed Wireshark v2.6.6  for my distro using `pacman`, then I cloned the LMP plugin repo and I ran the list of commands in the README (e.g.. `mkdir build` etc.).  Then when I opened Wireshark I did not have to setup any Decoding option.

**Comment by SamZorSec** [comment]
Thanks @francozappa, I got it working! Nice work. I used your last link for the plugin and Wireshark 2.6.8 (latest version from the package manager, Ubuntu 18.04).
